Standards:
  -
    Title: Intro To Lightning Talks
    Description: Intro To Lightning Talks
    UID: 07b2a8b0860efe7dee9b9eb34b11b7be
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 72afe16ca4f552e0a3de82224e7593fe
        Path: /intro-to-lightning-talks/intro-to-lightning-talks.md
      -
        Type: Lesson
        UID: e0c49e15078635de86976b6e6f39e2c6
        Path: /intro-to-lightning-talks/personal-introduction-talk.md
      -
        Type: Lesson
        UID: 085e5e9a2dac58a838c09f5bf67df941
        Path: /intro-to-lightning-talks/personal-introduction-submission.md
  -
    Title: Unit 1 Lightning Talks
    Description: Unit 1 Lightning Talks
    UID: 732ca6e35056871e2dc0747b954460f2
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 9ba86d17b5841d8f34757a69cbb3c9d3
        Path: /unit-1-lightning-talks/unit-1-talk.md
      -
        Type: Lesson
        UID: 2f0db7bfe571583ba88991e7e46a64c5
        Path: /unit-1-lightning-talks/unit-1-submission.md
  -
    Title: Unit 2 Lightning Talks
    Description: Unit 2 Lightning Talks
    UID: 6ace0e68cf34de1576d69a891328a002
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 9fa74d7cb684e4d9078818ad56f2c30d
        Path: /unit-2-lightning-talks/unit-2-talk.md
      -
        Type: Lesson
        UID: 04042f7b3bead0a3e3ec8f3cd1ab7e4c
        Path: /unit-2-lightning-talks/unit-2-submission.md
  -
    Title: Unit 3 Lightning Talks
    Description: Unit 3 Lightning Talks
    UID: 0083d647949c77c41077c9cb50a6028c
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: de7a3704f2a871f8ccb839a74c355a89
        Path: /unit-3-lightning-talks/unit-3-talk.md
      -
        Type: Lesson
        UID: bd79bc54a0ce09cec07a96fa28e2ddf1
        Path: /unit-3-lightning-talks/unit-3-submission.md
